apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "taskboard.fullname" . }}-backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {app: taskboard-backend}
  template:
    metadata:
      labels: {app: taskboard-backend}
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image }}:{{ .Values.backend.tag }}"
          ports: [{containerPort: 8000}]
          env:
            - name: DATABASE_URL
              value: "postgresql+psycopg://{{ .Values.postgres.username }}:{{ .Values.postgres.password }}@{{ .Values.postgres.host }}:5432/{{ .Values.postgres.database }}"
          readinessProbe:
            httpGet: {path: /ready, port: 8000}
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet: {path: /health, port: 8000}
            initialDelaySeconds: 20
            periodSeconds: 15
          resources:
{{ toYaml .Values.resources | indent 12 }}
